// TabZen Gemini Flash AI Client (ES Module)

const GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent";

/**
 * Direct call to Google Generative Language API
 */
export async function callGemini(apiKey, prompt, systemInstruction = "", responseMimeType = "text/plain") {
  if (!apiKey || !apiKey.trim()) {
    throw new Error("Missing Gemini API key. Please configure your API key in TabZen Settings.");
  }

  const url = `${GEMINI_API_URL}?key=${encodeURIComponent(apiKey.trim())}`;
  const payload = {
    contents: [{ parts: [{ text: prompt }] }],
    generationConfig: {
      temperature: 0.2,
      responseMimeType: responseMimeType
    }
  };

  if (systemInstruction) {
    payload.systemInstruction = { parts: [{ text: systemInstruction }] };
  }

  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload)
  });

  if (!response.ok) {
    const errorBody = await response.text();
    let message = `Gemini API error (${response.status})`;
    try {
      const parsed = JSON.parse(errorBody);
      if (parsed.error && parsed.error.message) {
        message = parsed.error.message;
      }
    } catch {
      // Use raw status
    }
    throw new Error(message);
  }

  const data = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) {
    throw new Error("No response content generated by Gemini.");
  }
  return text;
}

/**
 * Cluster tabs into meaningful topic groups using Gemini Flash
 */
export async function clusterTabsWithAI(apiKey, tabs) {
  if (!tabs || tabs.length === 0) return [];

  // Fallback heuristic clustering if no API key is provided
  if (!apiKey || !apiKey.trim()) {
    return clusterTabsHeuristic(tabs);
  }

  const systemInstruction = `You are an expert browser organizer. 
Given a JSON list of open browser tabs (id, title, url), organize them into 2 to 7 logical categories based on topic, project, or task.
Assign each group:
1. "name": A concise, descriptive group title (1-3 words, optionally starting with a relevant emoji).
2. "color": Choose ONE valid color strictly from: ["grey", "blue", "red", "yellow", "green", "pink", "purple", "cyan", "orange"].
3. "tabIds": An array of tab ID numbers belonging to this group.

Return STRICTLY a JSON object matching this schema:
{
  "groups": [
    {
      "name": "string",
      "color": "string",
      "tabIds": [number]
    }
  ]
}`;

  const tabsSummary = tabs.map(t => ({
    id: t.id,
    title: t.title,
    url: t.url
  }));

  const prompt = `Here are the active browser tabs:\n${JSON.stringify(tabsSummary, null, 2)}`;

  try {
    const raw = await callGemini(apiKey, prompt, systemInstruction, "application/json");
    const parsed = JSON.parse(raw);
    if (parsed && Array.isArray(parsed.groups)) {
      return parsed.groups;
    }
  } catch (err) {
    console.warn("AI clustering failed, falling back to heuristic:", err);
  }

  return clusterTabsHeuristic(tabs);
}

/**
 * Fallback heuristic clustering by domain / keywords
 */
export function clusterTabsHeuristic(tabs) {
  const domainBuckets = {};

  for (const tab of tabs) {
    let domain = "Other";
    try {
      const u = new URL(tab.url);
      domain = u.hostname.replace(/^www\./, "");
    } catch {
      // ignore
    }

    if (!domainBuckets[domain]) {
      domainBuckets[domain] = [];
    }
    domainBuckets[domain].push(tab.id);
  }

  const colors = ["blue", "purple", "green", "orange", "cyan", "pink", "yellow"];
  let colorIdx = 0;
  const groups = [];

  for (const [domain, tabIds] of Object.entries(domainBuckets)) {
    if (tabIds.length >= 2) {
      groups.push({
        name: domain,
        color: colors[colorIdx % colors.length],
        tabIds: tabIds
      });
      colorIdx++;
    }
  }

  // Any remaining single tabs into an "Assorted" or "Reading" group if >= 2
  const groupedIds = new Set(groups.flatMap(g => g.tabIds));
  const remainingIds = tabs.filter(t => !groupedIds.has(t.id)).map(t => t.id);
  if (remainingIds.length >= 2) {
    groups.push({
      name: "📑 Reading & Misc",
      color: "grey",
      tabIds: remainingIds
    });
  }

  return groups;
}

/**
 * Fast 2-sentence takeaway & reading time for Triage Card
 */
export async function getTabTakeaway(apiKey, tabInfo) {
  if (!apiKey || !apiKey.trim()) {
    return {
      takeaway: tabInfo.description || `Reading material from ${tabInfo.url}. Configure Gemini API key for smart AI takeaways.`,
      readTime: "3 min"
    };
  }

  const systemInstruction = `You are a concise reading assistant.
Given a webpage title, url, description, and text snippet, output:
1. "takeaway": Exactly 1 or 2 crisp sentences summarizing the core idea or practical value. No fluff or boilerplate.
2. "readTime": Estimated reading time, e.g. "4 min".

Return STRICTLY JSON:
{
  "takeaway": "string",
  "readTime": "string"
}`;

  const prompt = `Title: ${tabInfo.title}\nURL: ${tabInfo.url}\nDescription: ${tabInfo.description || "N/A"}\nSnippet: ${(tabInfo.snippet || "").slice(0, 1500)}`;

  try {
    const raw = await callGemini(apiKey, prompt, systemInstruction, "application/json");
    const parsed = JSON.parse(raw);
    return {
      takeaway: parsed.takeaway || "Summary not available.",
      readTime: parsed.readTime || "3 min"
    };
  } catch (err) {
    console.warn("Gemini takeaway generation failed:", err);
    return {
      takeaway: tabInfo.description || "Article unread in your tabs.",
      readTime: "3 min"
    };
  }
}

/**
 * Deep 3-bullet summary when user clicks "⚡ Summarize & Close"
 */
export async function getDeepSummary(apiKey, tabInfo) {
  if (!apiKey || !apiKey.trim()) {
    return {
      takeaway: tabInfo.description || "Stashed article.",
      bullets: ["Saved without AI summary (no API key configured)."],
      readTime: "3 min"
    };
  }

  const systemInstruction = `You are an executive researcher.
Provide a high-yield summary for the given webpage.
Output:
1. "takeaway": A 1-sentence high level conclusion.
2. "bullets": Exactly 3 detailed bullet points capturing key facts, insights, or takeaways.
3. "readTime": Estimated reading time.

Return STRICTLY JSON:
{
  "takeaway": "string",
  "bullets": ["bullet 1", "bullet 2", "bullet 3"],
  "readTime": "string"
}`;

  const prompt = `Title: ${tabInfo.title}\nURL: ${tabInfo.url}\nDescription: ${tabInfo.description || "N/A"}\nSnippet: ${(tabInfo.snippet || "").slice(0, 2500)}`;

  try {
    const raw = await callGemini(apiKey, prompt, systemInstruction, "application/json");
    const parsed = JSON.parse(raw);
    return {
      takeaway: parsed.takeaway || tabInfo.title,
      bullets: parsed.bullets || [],
      readTime: parsed.readTime || "3 min"
    };
  } catch (err) {
    console.warn("Gemini deep summary failed:", err);
    return {
      takeaway: tabInfo.description || tabInfo.title,
      bullets: ["Key takeaways could not be retrieved from AI."],
      readTime: "3 min"
    };
  }
}
